# Generated by Django 2.2.2 on 2019-07-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='status',
            field=models.IntegerField(choices=[(0, 'updated'), (2, 'update_failed'), (1, 'update_in_progress'), (3, 'deleted_on_github')], default=0),
        ),
    ]
