# Generated by Django 2.2.2 on 2019-06-16 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0002_auto_20190616_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='github_integration.Branch'),
        ),
    ]
