# Generated by Django 2.2.2 on 2019-06-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0002_repository_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
