# Generated by Django 2.2.2 on 2019-06-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0006_auto_20190617_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='status',
            field=models.IntegerField(choices=[(0, 'updated'), (1, 'update_in_progress'), (2, 'deleted_on_github')], default=0),
        ),
    ]
