# Generated by Django 2.2.2 on 2019-06-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='branch',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'in progress'), (2, 'in review'), (3, 'completed')], default=0),
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
