# Generated by Django 2.2.2 on 2019-06-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0001_initial'),
        ('core', '0003_auto_20190620_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='branches',
            field=models.ManyToManyField(related_name='tasks', to='github_integration.Branch'),
        ),
    ]
