# Generated by Django 2.2.2 on 2019-06-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_invite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', 'deadline', 'status']},
        ),
    ]
