# Generated by Django 2.2.2 on 2019-06-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190623_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
