# Generated by Django 2.2.2 on 2019-06-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_sync_with_github',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
