# Generated by Django 2.2.2 on 2019-06-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190624_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='github_integration.Branch'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(choices=[(0, 'task'), (1, 'sub_task')], default=0),
        ),
    ]
