# Generated by Django 2.2.2 on 2019-06-25 07:50

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0012_auto_20190624_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('activity_type', models.IntegerField(choices=[(0, 'task was created'), (1, 'task was updated'), (2, 'task was completed'), (3, 'branch was updated')])),
                ('context', django.contrib.postgres.fields.hstore.HStoreField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
