# Generated by Django 2.2.2 on 2019-06-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
