# Generated by Django 2.2.2 on 2019-06-26 12:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190626_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='context',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
