# Generated by Django 2.2.2 on 2019-06-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190612_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
